-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.games
(
    id serial NOT NULL,
    name character varying COLLATE pg_catalog."default",
    price numeric(5, 2),
    CONSTRAINT games_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ownedgames
(
    id serial NOT NULL,
    game_id integer NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT ownedgames_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sales
(
    id serial NOT NULL,
    game_id integer,
    discount numeric(5, 4),
    CONSTRAINT sales_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    nickname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.ownedgames
    ADD CONSTRAINT game_id FOREIGN KEY (game_id)
    REFERENCES public.games (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.ownedgames
    ADD CONSTRAINT user_id FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sales
    ADD CONSTRAINT sales_game_id_fkey FOREIGN KEY (game_id)
    REFERENCES public.games (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;